---
- hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: choose system
    import_tasks: centos.yml
    when: ansible_facts['os_family'] == "RedHat"
  - import_tasks: ubuntu.yml
    when: ansible_facts['os_family'] == "Debian"  

